jobs:

- job:
  displayName: "Ubuntu 16.04"
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment python=$PYTHON_VERSION dask lxml matplotlib numpy pathlib pyqt pyqtgraph requests
    displayName: Install Anaconda packages

  - bash: |
      source activate myEnvironment
      python setup.py bdist_wheel --universal
      for f in dist/FMPy-*.whl; do
        pip install $f --no-deps -vv
      done
      cd tests
      python -m unittest discover
      cd ..
    displayName: Build, install and run tests
