jobs:

- job:
  displayName: "Ubuntu 16.04"
  strategy:
    matrix:
      linux27:
        imageName: 'ubuntu-16.04'
        python.version: '2.7'
      linux36:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      mac27:
        imageName: 'macos-10.13'
        python.version: '2.7'
      mac36:
        imageName: 'macos-10.13'
        python.version: '3.6'
      windows27:
        imageName: 'vs2017-win2016'
        python.version: '2.7'
      windows36:
        imageName: 'vs2017-win2016'
        python.version: '3.6'
  pool:
    vmImage: $(imageName)
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name myEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate myEnvironment
      conda install --yes --quiet --name myEnvironment -c conda-forge python=$PYTHON_VERSION dask lxml matplotlib numpy pathlib pyqt pyqtgraph pytest-cov requests
    displayName: Install Anaconda packages

  - bash: |
      source activate myEnvironment
      python setup.py bdist_wheel --universal
      for f in dist/FMPy-*.whl; do
        pip install $f --no-deps -vv
      done
      cd tests
      pytest --junitxml=junit/test-results.xml --cov=fmpy --cov-report=xml --cov-report=html
      cd ..
    displayName: Build, install and run tests

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
